# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-03 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190102_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 0, 25, 45, 58303, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 0, 25, 45, 57298, tzinfo=utc)),
        ),
    ]
