# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-03 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190102_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 0, 30, 18, 691316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 0, 30, 18, 690318, tzinfo=utc)),
        ),
    ]
